
export default function Home(){
    return(
        <>
        oi essa é a minha home...
        Estou inserindo um commit...
        Vamos subir uma alteracao...
        Atualização para subir automatico...
        </>
    )
}